import React, { useState, useEffect } from 'react';
import { Dimensions, StyleSheet, Pressable, SafeAreaView, StatusBar, View, Text } from 'react-native';
import { retrieveTemplate, updateTemplate } from '../api.js';

import { JoyDoc } from '@joyfill/components-react-native';

const screenWidth = Dimensions.get('window').width;

function App() {

  const [ template, setTemplate ] = useState(null);

  /**
   * Add your template identifier
   */
  const identifier = '<REPLACE_WITH_TEMPLATE_IDENIFIER>';

  /**
   * Retrieve template via the Joyfill API 
   */
  useEffect(() => {

    const handleRetrieveTemplate = async () => {
      const response = await retrieveTemplate(identifier);
      setTemplate(response);
    };

    handleRetrieveTemplate();

  }, []);

  const handleTemplateUpdate = async () => {
    const response = await updateTemplate(identifier, template);
    setTemplate(response);
  };

  return (
    <SafeAreaView style={Styles.container}>
      <StatusBar />
      <View style={Styles.form}>
        <JoyDoc
          mode="fill"
          doc={template}
          width={screenWidth}
          onChange={(changelogs, data) => {

            /**
             * Changelogs represent the individual change that was made
             * Data represents the entire data structure with all new changes applied.
             */
            console.log('>>>>>>>>: ', changelogs, data);

            /**
             * Set the latest document generated by the SDK so that we can save it to the Joyfill API.
             */
            setTemplate(data);

          }}
        />
        <View style={Styles.actions}>
          <Pressable
            style={Styles.button}
            onPress={handleTemplateUpdate}
          >
            <Text style={Styles.buttonText}>Save Changes</Text>
          </Pressable>
        </View>
      </View>
    </SafeAreaView>
  );

}

const Styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  form: {
    flex: 1,
    backgroundColor: 'white',
    padding: 2,
  },
  button: {
    backgroundColor: 'white',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1E90FF',
    padding: 10,
  },
  buttonText: {
    color: '#1E90FF',
  },
  row: {
    margin: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  highlight: {
    fontWeight: '700',
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: 'black',
  },
  actions: {
    height: 40,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  button: {
    borderWidth: 1,
    borderColor: "#276FFA",
    borderRadius: 5,
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12
  },
  buttonText: {
    color: "#276FFA",
    fontWeight: 'bold',
  }

});

export default App;
